// tslint:disable
/**
 * HastaTakipBack
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import { FormFunctionsApi, FormsFunctionsApi, ListFunctionsApi, LocationFunctionsApi, ProjectFunctionsApi, UserFunctionsApi } from "./api";
import { Configuration } from "./configuration";

export * from "./api";
export * from "./configuration";

export const basePath = 'http://localhost:7400'


const defaultConfig = new Configuration({ basePath })
export const userApi = new UserFunctionsApi(defaultConfig);
export const projectApi = new ProjectFunctionsApi(defaultConfig);
export const formApi = new FormFunctionsApi(defaultConfig);
export const formsApi = new FormsFunctionsApi(defaultConfig);
export const listApi = new ListFunctionsApi(defaultConfig);
export const locationApi = new LocationFunctionsApi(defaultConfig);